name: MineTopFakePlayers
version: 1.0.0
main: in.minetop.fakeplayers.paper.MineTopFakePlayersPaper
api-version: '1.21'
author: MineTop
commands:
  fakeplayer:
    description: Manage MineTop fake player NPCs
    usage: /fakeplayer <create|tp|move|remove|list|reload>
    aliases: [fp]
permissions:
  minetop.fakeplayers.admin:
    description: Allows management of fake player NPCs
    default: op
